# Generated by Django 3.2 on 2020-09-21 21:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('account_name', models.CharField(max_length=50)),
                ('max_bench', models.IntegerField()),
                ('max_squat', models.IntegerField()),
                ('max_deadlift', models.IntegerField()),
                ('max_ohp', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Lift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lift_name', models.CharField(choices=[('Squat', 'Squat'), ('Bench', 'Bench'), ('Deadlift', 'Deadlift'), ('Overhead Press', 'Overhead Press')], default='Squat', max_length=15)),
                ('reps', models.IntegerField()),
                ('weight', models.IntegerField()),
                ('Account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='workout.account')),
            ],
        ),
    ]
