# Generated by Django 3.2 on 2020-09-21 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workout', '0002_lift_lift_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='days_worked',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
